"""
All core data structures used across the system.
Defined here and imported by all components — no component defines its own models.
No third-party dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, date
from typing import Dict, Literal, List


# ---------------------------------------------------------------------------
# Market data
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class OHLCVBar:
    """One 1-minute OHLCV bar. Immutable."""
    ticker:    str
    timestamp: datetime   # UTC, bar close time
    open:      float
    high:      float
    low:       float
    close:     float
    volume:    float


# ---------------------------------------------------------------------------
# Machine state
# ---------------------------------------------------------------------------

@dataclass
class MachineStatus:
    """
    The runtime state of the trading machine. One instance per session.
    Owned by TradingMachine and passed explicitly to every component.
    """
    position:          Literal["IDLE", "LONG"]
    active_stop_price: float | None      # current stop-loss price; None when IDLE or unknown
    initial_nav:       float             # NAV at session start (cash + value of shares)
    daily_start_nav:   float             # NAV at start of current trading day; reset by coordinator on day boundary
    session_date:      date              # calendar date of the current session (EST)
    pending_orders:    Dict[str, Literal["BUY", "SELL"]]  # order_id → side; {} when no open orders
    bar_count:         int               # total bars processed this session (for pivot timing)


# ---------------------------------------------------------------------------
# Order types
# ---------------------------------------------------------------------------

@dataclass
class AnalystOrder:
    """
    An instruction from the analyst to the trader.
    The trader translates these into BrokerOrder objects.
    """
    type: Literal[
        "CANCEL_ALL_BUYS",
        "BUY_LIMIT",
        "SELL_STOP",
        "SELL_MARKET",
        "UPDATE_STOPLOSS",
    ]
    price:        float | None = None    # limit price (BUY_LIMIT, SELL_STOP, UPDATE_STOPLOSS)
    size:         Literal["FULL_AVAILABLE_CASH", "ALL_SHARES"] | None = None
    condition:    str | None = None      # e.g. "on_fill:<order_id>"


@dataclass
class BrokerOrder:
    """
    A structured order ready to be sent to the broker bus.
    Produced by the trader; never constructed by the analyst.
    """
    order_id:     str                    # UUID generated by the trader
    ticker:       str
    side:         Literal["BUY", "SELL"]
    order_type:   Literal["LIMIT", "MARKET", "STOP", "CANCEL"]
    limit_price:  float | None           # None for MARKET and STOP orders
    quantity:     float                  # number of shares (computed by trader from cash)
    condition:    str | None             # conditional execution instruction
    created_at:   datetime
    stop_price:   float | None = None    # trigger price for STOP orders; None otherwise


# ---------------------------------------------------------------------------
# Execution & ledger
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExecutionConfirmation:
    """
    Returned by the broker bus (live or test) when an order is filled.
    Immutable — never modified after receipt.
    """
    confirmation_id: str                 # broker-assigned; used for deduplication
    order_id:        str                 # matches BrokerOrder.order_id
    ticker:          str
    side:            Literal["BUY", "SELL"]
    filled_quantity: float
    filled_price:    float
    filled_at:       datetime            # UTC


@dataclass(frozen=True)
class LedgerEntry:
    """
    One record per execution confirmation. Appended by the bookkeeper; never modified.
    """
    entry_id:        str                 # UUID
    confirmation_id: str                 # from ExecutionConfirmation (for traceability)
    ticker:          str
    side:            Literal["BUY", "SELL"]
    quantity:        float
    price:           float
    gross_value:     float               # quantity * price
    fee:             float               # broker fee (0.0 if unknown/test)
    net_value:       float               # gross_value + fee (cost is positive)
    cash_after:      float               # bookkeeper cash balance after this entry
    shares_after:    float               # bookkeeper shares held after this entry
    timestamp:       datetime            # UTC
    note:            str                 # free text, e.g. "stop-loss triggered"
