"""
All core data structures used across the system.
Defined here and imported by all components — no component defines its own models.
No third-party dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, date
from typing import Literal, List


# ---------------------------------------------------------------------------
# Market data
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class OHLCVBar:
    """One 1-minute OHLCV bar. Immutable."""
    ticker:    str
    timestamp: datetime   # UTC, bar close time
    open:      float
    high:      float
    low:       float
    close:     float
    volume:    float


# ---------------------------------------------------------------------------
# Machine state
# ---------------------------------------------------------------------------

@dataclass
class MachineStatus:
    """
    The runtime state of the trading machine. One instance per session.
    Owned by TradingMachine and passed explicitly to every component.

    # REVIEW: architecture.md omits the `bar_count` field that data_model.md
    # includes. Using data_model.md as the authoritative source for data
    # structures. Verify this is intentional.
    """
    position:          Literal["IDLE", "LONG"]
    watermark_level:   int | None        # index into current pivots list; None when IDLE
    initial_nav:       float             # NAV at session start (cash + value of shares)
    session_date:      date              # calendar date of the current session (EST)
    pending_order_ids: List[str]         # broker-assigned IDs of unconfirmed orders
    bar_count:         int               # total bars processed this session (for pivot timing)


# ---------------------------------------------------------------------------
# Order types
# ---------------------------------------------------------------------------

@dataclass
class AnalystOrder:
    """
    An instruction from the analyst to the trader.
    The trader translates these into BrokerOrder objects.

    # REVIEW: analyst_logic.md uses the keyword `new_price` when constructing
    # UPDATE_STOPLOSS orders (e.g. AnalystOrder(type="UPDATE_STOPLOSS", new_price=...))
    # but the data model defines the field as `price`. Using `price` here (data_model.md
    # is authoritative). The analyst implementation must use `price=` not `new_price=`.
    """
    type: Literal[
        "CANCEL_ALL_BUYS",
        "BUY_LIMIT",
        "SELL_LIMIT",
        "SELL_MARKET",
        "UPDATE_STOPLOSS",
    ]
    price:        float | None = None    # limit price (BUY_LIMIT, SELL_LIMIT, UPDATE_STOPLOSS)
    size:         Literal["FULL_AVAILABLE_CASH", "ALL_SHARES"] | None = None
    condition:    str | None = None      # e.g. "on_fill:<order_id>"
    watermark:    int | None = None      # new watermark level, if updated by this order


@dataclass
class BrokerOrder:
    """
    A structured order ready to be sent to the broker bus.
    Produced by the trader; never constructed by the analyst.
    """
    order_id:     str                    # UUID generated by the trader
    ticker:       str
    side:         Literal["BUY", "SELL"]
    order_type:   Literal["LIMIT", "MARKET", "STOP_LIMIT"]
    limit_price:  float | None           # None for MARKET orders
    quantity:     float                  # number of shares (computed by trader from cash)
    condition:    str | None             # conditional execution instruction
    created_at:   datetime


# ---------------------------------------------------------------------------
# Execution & ledger
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExecutionConfirmation:
    """
    Returned by the broker bus (live or fake) when an order is filled.
    Immutable — never modified after receipt.
    """
    confirmation_id: str                 # broker-assigned; used for deduplication
    order_id:        str                 # matches BrokerOrder.order_id
    ticker:          str
    side:            Literal["BUY", "SELL"]
    filled_quantity: float
    filled_price:    float
    filled_at:       datetime            # UTC


@dataclass(frozen=True)
class LedgerEntry:
    """
    One record per execution confirmation. Appended by the bookkeeper; never modified.
    """
    entry_id:        str                 # UUID
    confirmation_id: str                 # from ExecutionConfirmation (for traceability)
    ticker:          str
    side:            Literal["BUY", "SELL"]
    quantity:        float
    price:           float
    gross_value:     float               # quantity * price
    fee:             float               # broker fee (0.0 if unknown/fake)
    net_value:       float               # gross_value + fee (cost is positive)
    cash_after:      float               # bookkeeper cash balance after this entry
    shares_after:    float               # bookkeeper shares held after this entry
    timestamp:       datetime            # UTC
    note:            str                 # free text, e.g. "stop-loss triggered"
